### ISSUE TITLE
Enabling Toast Notifications

### ISSUE THREAD

**Issue by lean0x2F** [fox-it/Invoke-CredentialPhisher#3]
First of all, great work Rindert!

I was having issues with a computer where there was no way to spawn notifications. I realized that it was because toast notifications were disabled on that system. These notifications can be re-enabled from the new control panel without needing to elevate privileges. I monitored the registry modifications and found the key responsible for this:

![image](https://user-images.githubusercontent.com/19156572/48867376-bf0d0d80-edb4-11e8-8e64-2e3b9e94af3e.png)

That would be translated to powershell as:

``` Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\PushNotifications" -Name "ToastEnabled" -Type DWord -Value 1 ```

Adding that to the script would be a nice idea, as the responsible key lies in HKCU (we don't need privileges to write there). However, this is not practical as it requires a system restart. I don't have enough Windows knowledge to figure out how these settings are updated "on the fly" by Windows. 

Any ideas?

Thanks!

**Comment by lean0x2F** [comment]
Hi! I figured it out. A simple way to trigger an update in the notification service settings would be to simply restart the service. To re-enable notifications on the systems that have notifications turned off we could just run:

```
# Modify registry key that manages balloon notifications
Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\PushNotifications" -Name "ToastEnabled" -Type DWord -Value 1
# Restart the push notification service. This service is usually appended with a random string such as "_0e48d", so we just use globbing
Restart-Service -Name "WpnUserService*"
```

**Comment by rindert-fox** [comment]
Hi, thanks!

I added the switch `-EnableToastNotificationsIfDisabled` to enable toast notifications with the registry key you mentioned and restart the corresponding service. It is not enabled by default, since toast notifications work on my computer without this registry key, so I am a bit hesitant to run these cmdlets by default.
